[global]

# If True, will show a warning when you run a Streamlit-enabled script via "python my_script.py".
# Default: true
showWarningOnDirectExecution = true

[logger]

# Level of logging: 'error', 'warning', 'info', or 'debug'.
# Default: 'info'
level = "info"

[client]

# Controls whether uncaught app exceptions are displayed in the browser. By default, this is set to True and Streamlit displays app exceptions and associated tracebacks in the browser.
# Default: true
showErrorDetails = true

[server]

# Configuration optimized for Streamlit Cloud deployment
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

# File upload settings
maxUploadSize = 200
maxMessageSize = 200

# Performance settings
enableWebsocketCompression = false

[browser]

# Streamlit Cloud optimized browser settings
gatherUsageStats = false

# [mapbox] section removed - deprecated, use MAPBOX_API_KEY environment variable instead

# [deprecation] section removed - these options are no longer valid

[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
# base = 

# Primary accent color for interactive elements.
primaryColor = "#0047AB"

# Background color for the main content area.
# backgroundColor = 

# Background color used for the sidebar and most interactive widgets.
# secondaryBackgroundColor = 

# Color used for almost all text.
# textColor = 

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# font =
